version: '3.5'
services:
    wordpress:
        build:
            context: ./
            dockerfile: ./Dockerfile
        links:
            - db:mysql
            - mailhog
        ports:
            - 80:80
        domainname: ${WORDPRESS_URL}
        hostname: ${WORDPRESS_URL}
        volumes:
            - ./public:/var/www/html
            - ./wordpress/themes:/var/www/html/wp-content/themes:rw
            - ./wordpress/plugins:/var/www/html/wp-content/plugins:rw
            - ./wordpress/uploads:/var/www/html/wp-content/uploads:rw
            - ./phpconf.ini:/usr/local/etc/php/conf.d/phpconf.ini
        environment:
            WORDPRESS_DB_PASSWORD: docker
            WORDPRESS_DEBUG: 1
        depends_on:
            - mailhog
            - db

    mailhog:
        image: mailhog/mailhog
        ports:
            - 1025:1025
            - 8025:8025

    wpcli:
        image: wordpress:cli
        volumes:
            - ./public:/var/www/html
        command: wp core install --path="/var/www/html" --url=${WORDPRESS_URL} --title="${WORDPRESS_TITLE}" --admin_user=${ADMIN_USER} --admin_password=${ADMIN_PASSWORD} --admin_email=${ADMIN_EMAIL}
        restart: on_failure
        links:
            - db:mysql
        depends_on: 
            - db
            - wordpress

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: docker
        volumes:
            - ./db-data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports: 
            - 81:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
        depends_on:
            - db